Repository Stop-smoke/KekKek, pull requests merged in 2024-07, with the labels that each got.

#191 Create README.md
  README.md
Labels: documentation

#198 [KEKKEK-32] 게시글, 댓글, 대댓글 생성 시간 불일치 문제 해결
  app/src/main/java/com/stopsmoke/kekkek/core/data/mapper/DateTimeMapper.kt
  app/src/main/java/com/stopsmoke/kekkek/core/data/mapper/UserMapper.kt
Labels: bug

#199 [KEKKEK-26] feat: 커뮤니티 상단으로 이동하기 위한 반응형 플로팅 버튼 추가
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityFragment.kt
  app/src/main/res/drawable/btn_circle_white.xml
  app/src/main/res/drawable/ic_community_btn_top.xml
  app/src/main/res/layout/fragment_community.xml
Labels: feature

#203 [KEKKEK-72] 새로운 댓글 삭제, 좋아요 버튼 작동하지 않는 문제 해결
  app/src/main/java/com/stopsmoke/kekkek/core/data/repository/ReplyRepositoryImpl.kt
  app/src/main/java/com/stopsmoke/kekkek/core/domain/repository/ReplyRepository.kt
  app/src/main/java/com/stopsmoke/kekkek/core/firestore/dao/ReplyDao.kt
  app/src/main/java/com/stopsmoke/kekkek/core/firestore/data/ReplyDaoImpl.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/dialog/CircularProgressDialogFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/dialog/CommonDialogFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/dialog/CommonDialogListener.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/detail/PostDetailFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/detail/PostDetailViewModel.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/detail/adapter/PreviewCommentAdapter.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/detail/callback/PostCommentCallback.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/detail/dialog/DeleteDialogType.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/detail/dialog/PostCommentDeleteDialogFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/detail/viewholder/PostReplyViewHolder.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/detail/viewholder/PreviewCommentHolder.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/edit/PostEditFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/reply/ReplyViewModel.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/profile/SettingsProfileFragment.kt
  app/src/main/res/layout/fragment_circular_progress_dialog.xml
  app/src/main/res/layout/fragment_common_dialog.xml
  app/src/main/res/values/strings.xml
Labels: fix

#204 [KEKKEK-53] 게시글 카테고리 설정 스피너 삭제 및 바텀 다이얼로그로 수정, PostEdit 전체 UI 수정
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/edit/PostEditFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/edit/dialog/PostEditBottomSheetDialog.kt
  app/src/main/res/drawable/ic_category.xml
  app/src/main/res/drawable/ic_dropdown.xml
  app/src/main/res/layout/fragment_post_edit.xml
  app/src/main/res/layout/fragment_post_edit_app_bar.xml
  app/src/main/res/layout/fragment_post_edit_bottomsheet_dialog.xml
  app/src/main/res/layout/fragment_post_write_app_bar.xml
  app/src/main/res/values/strings.xml
Labels: feature, design

#208 [KEKKEK-84] Firebase messaging 정상 작동하지 않는 문제 해결
  app/src/main/java/com/stopsmoke/kekkek/core/data/repository/UserRepositoryImpl.kt
  app/src/main/java/com/stopsmoke/kekkek/core/domain/usecase/RegisterFcmTokenUseCase.kt
  app/src/main/java/com/stopsmoke/kekkek/core/firemseeage/FirebaseMessagingDataSource.kt
  app/src/main/java/com/stopsmoke/kekkek/core/firemseeage/di/FirebaseMessagingModule.kt
  app/src/main/java/com/stopsmoke/kekkek/core/firestore/dao/UserDao.kt
  app/src/main/java/com/stopsmoke/kekkek/core/firestore/data/UserDaoImpl.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/onboarding/OnboardingViewModel.kt
  gradle/libs.versions.toml
Labels: fix
