Repository Stop-smoke/KekKek, pull requests merged in 2024-06, with the labels that each got.

#30 [#14] Feat: 금연 성과(Attainments) 프래그먼트 및 로직 구현
  app/build.gradle.kts
  app/src/main/java/com/stopsmoke/kekkek/domain/Utils.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/attainments/AttainmentsFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/attainments/AttainmentsViewModel.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/home/HomeFragment.kt
  app/src/main/res/drawable/bg_attainments_box.xml
  app/src/main/res/drawable/ic_attainments_cash.xml
  app/src/main/res/drawable/ic_attainments_heartbox.xml
  app/src/main/res/drawable/ic_attainments_smoke.xml
  app/src/main/res/drawable/ic_attainments_thumbsup.xml
  app/src/main/res/layout/fragment_attainments.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/menu/menu_attainments_toolbar.xml
  app/src/main/res/navigation/nav_graph.xml
  gradle/libs.versions.toml
Labels: feature

#31 Feature/#20 post
  app/build.gradle.kts
  app/src/main/java/com/stopsmoke/kekkek/PostWriteFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/post/PostViewFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/post/PostWriteFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/post/PostWriteItem.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityFragment.kt
  app/src/main/res/drawable/ic_category.xml
  app/src/main/res/drawable/ic_editor_1.png
  app/src/main/res/drawable/ic_editor_2.png
  app/src/main/res/drawable/ic_editor_3.png
  app/src/main/res/drawable/ic_editor_4.png
  app/src/main/res/drawable/ic_editor_5.png
  app/src/main/res/drawable/ic_editor_6.png
  app/src/main/res/drawable/ic_editor_7.png
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/fragment_post_view.xml
  app/src/main/res/layout/fragment_post_write.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/array.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: bug, feature

#33 design, fix: Bottom Navigation 수정, 커뮤니티 프래그먼트 오류 수정
  app/src/main/java/com/stopsmoke/kekkek/presentation/MainActivity.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/attainments/AttainmentsFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/home/HomeFragment.kt
  app/src/main/res/color/bottom_nav_color.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/menu/bottom_navigation_view.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: bug, design

#38 refac: community Ui 카테고리 위에 고정되도록 desing, code 변경
  app/src/main/java/com/stopsmoke/kekkek/DummyData.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/bookmark/BookmarkListAdapter.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/bookmark/BookmarkUiState.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityListAdapter.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityListItem.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityUiState.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityViewModel.kt
  app/src/main/res/layout/fragment_community.xml
  app/src/main/res/layout/item_community_postcategory.xml
  app/src/main/res/layout/item_community_top.xml
Labels: feature, design

#40 Enhancement/post
  app/build.gradle.kts
  app/src/main/java/com/stopsmoke/kekkek/post/PostWriteItem.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityListAdapter.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityListItem.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/MyCommentFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/MyFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/MyPostFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostViewFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostWriteFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostWriteItem.kt
  app/src/main/res/drawable/ic_my_comment.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_my_comment.xml
  app/src/main/res/layout/fragment_my_post.xml
  app/src/main/res/layout/fragment_post_view.xml
  app/src/main/res/layout/fragment_post_write.xml
  app/src/main/res/layout/recyclerview_my_comment_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#44 Enhancement/post
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/MyCommentFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/MyFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/MyPostFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostWriteFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/LanguageFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/MultiViewEnum.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/NotificationFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/OnClickListener.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/ProfileFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/SettingAdapter.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/SettingFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/SettingItem.kt
  app/src/main/res/layout/fragment_language.xml
  app/src/main/res/layout/fragment_notification_setting.xml
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_setting.xml
  app/src/main/res/layout/item_setting_list.xml
  app/src/main/res/layout/item_setting_profile.xml
  app/src/main/res/layout/item_setting_version.xml
  app/src/main/res/layout/unknown_item.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#45 feat, refactor: 지원, 개인정보 보호웹뷰 구현, oss 설정, 이름 및 패키징 변경, 오류 수정 등
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/stopsmoke/kekkek/presentation/home/HomeFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/home/HomeViewModel.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/LanguageFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/NotificationFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/OnClickListener.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/SettingsAdapter.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/SettingsFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/language/SettingsLanguageFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/model/MultiViewEnum.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/model/OnClickListener.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/model/SettingsItem.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/notification/SettingsNotificationFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/opensource/SettingsOpensourceFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/privatepolicy/SettingsPrivatePolicyFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/profile/SettingsProfileFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/support/SettingsSupportFragment.kt
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_settings_language.xml
  app/src/main/res/layout/fragment_settings_notification.xml
  app/src/main/res/layout/fragment_settings_opensource.xml
  app/src/main/res/layout/fragment_settings_private_policy.xml
  app/src/main/res/layout/fragment_settings_profile.xml
  app/src/main/res/layout/fragment_settings_support.xml
  app/src/main/res/layout/fragment_user_profile_app_bar.xml
  app/src/main/res/layout/item_settings_list.xml
  app/src/main/res/layout/item_settings_profile.xml
  app/src/main/res/layout/item_settings_version.xml
  app/src/main/res/navigation/nav_graph.xml
  build.gradle.kts
  gradle/libs.versions.toml
Labels: bug, enhancement, refactor

#48 Enhancement/setting
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/SettingsFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/language/SettingsLanguageFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/notification/SettingsNotificationFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/profile/SettingsProfileFragment.kt
  app/src/main/res/drawable/ic_profile_edit.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/fragment_settings_language.xml
  app/src/main/res/layout/fragment_settings_notification.xml
  app/src/main/res/layout/fragment_settings_profile.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/strings.xml
Labels: feature

#56 Enhancement/data
  app/src/main/java/com/stopsmoke/kekkek/presentation/home/HomeFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/test/QuestionFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/test/TestAdapter.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/test/TestFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/test/TestQuestionFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/test/TestResultFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/test/TestViewModel.kt
  app/src/main/res/drawable/bg_text_button.xml
  app/src/main/res/drawable/custom_ripple_effect.xml
  app/src/main/res/drawable/ic_cancel.xml
  app/src/main/res/drawable/ic_smoke.xml
  app/src/main/res/layout/fragment_question.xml
  app/src/main/res/layout/fragment_test_onboarding.xml
Labels: feature

#61 Enhancement/data
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/stopsmoke/kekkek/domain/repository/PostRepository.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityListAdapter.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityListItem.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/home/HomeFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostViewFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostViewModel.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostWriteFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/test/TestViewModel.kt
  app/src/main/res/drawable/bg_comment_register.xml
  app/src/main/res/drawable/ic_post.xml
  app/src/main/res/layout/fragment_post_view.xml
  app/src/main/res/layout/item_comment.xml
  app/src/main/res/layout/item_community_postwriting.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/nav_settings.xml
Labels: enhancement

#63 fix: nav_graph 에서 nav_setting 으로 분리, 설정 들어갈때 앱 다운되는 현상 해결
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/MyFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/SettingsFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/profile/SettingsProfileFragment.kt
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/navigation/nav_settings.xml
Labels: bug

#76 Enhancement/data
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityListItem.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/MyFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/smokingsetting/SmokingPerDayFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/smokingsetting/SmokingPerPackFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/smokingsetting/SmokingPriceFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/smokingsetting/SmokingSettingFinishFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/myBookmarkList/BookmarkFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostViewFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostViewModel.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostWriteFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/profile/SettingsProfileFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/test/TestQuestionFragment.kt
  app/src/main/res/drawable/ic_bookmark.xml
  app/src/main/res/drawable/ic_bookmark_filled.xml
  app/src/main/res/layout/fragment_post_view.xml
  app/src/main/res/layout/fragment_post_view_app_bar.xml
  app/src/main/res/layout/fragment_post_write.xml
  app/src/main/res/layout/fragment_question.xml
  app/src/main/res/layout/fragment_settings_profile.xml
  app/src/main/res/layout/fragment_smoking_per_day.xml
  app/src/main/res/layout/fragment_smoking_per_pack.xml
  app/src/main/res/layout/fragment_smoking_price.xml
  app/src/main/res/layout/fragment_smoking_setting_finish.xml
  app/src/main/res/layout/profile_edit_introduction.xml
  app/src/main/res/layout/profile_edit_nickname.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/array.xml
Labels: enhancement

#84 Enhancement/data
  app/src/androidTest/java/com/stopsmoke/kekkek/firestore/dao/CommentDaoInstrumentedTest.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/home/HomeFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/smokingsetting/SmokingPerDayFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/smokingsetting/SmokingPerPackFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/smokingsetting/SmokingPriceFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/my/smokingsetting/SmokingSettingFinishFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/myBookmarkList/BookmarkFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/notification/NotificationFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/settings/SettingsFragment.kt
Labels: enhancement

#89 [#86] feat, design: 게시글 삭제/신고 기능 구현, 수정프로필 기본 이미지 수정 등
  app/src/main/java/com/stopsmoke/kekkek/data/repository/PostRepositoryImpl.kt
  app/src/main/java/com/stopsmoke/kekkek/domain/model/Post.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/MainActivity.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/community/CommunityViewModel.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostViewFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/PostViewModel.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/post/edit/PostEditFragment.kt
  app/src/main/res/drawable/img_default_pleaseset.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_post_view_bottomsheet_dialog.xml
  app/src/main/res/layout/fragment_settings_profile.xml
  app/src/main/res/layout/fragment_user_profile.xml
  app/src/main/res/layout/fragment_user_profile_detail.xml
  app/src/main/res/layout/recyclerview_user_profile_comment.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: feature, design

#111 [#109] design: 바텀 네비게이션을 컨스트레인트로 구현 후 커스텀
  app/build.gradle.kts
  app/src/main/java/com/stopsmoke/kekkek/presentation/MainActivity.kt
  app/src/main/java/com/stopsmoke/kekkek/util.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_bookmark_app_bar.xml
  app/src/main/res/menu/bottom_navigation_view.xml
Labels: design

#155 design: 프로필 이미지 변경 하단 표시 추가
  app/src/main/res/drawable/bg_settings_profile_edit.xml
  app/src/main/res/layout/fragment_settings_profile.xml
Labels: enhancement, design

#159 feat, design: 에러 핸들링용 프래그먼트 추가, UI (없는 페이지, 각종 오류 대응 페이지), 추천 검색어 색상 및 마진 설정, 검색 배경 설정 등
  app/src/main/java/com/stopsmoke/kekkek/presentation/errorhandler/ErrorMissingFragment.kt
  app/src/main/java/com/stopsmoke/kekkek/presentation/errorhandler/ErrorServerEtcFragment.kt
  app/src/main/res/drawable/bg_search_recommended.xml
  app/src/main/res/drawable/img_error_emoji.png
  app/src/main/res/layout/fragment_community_app_bar.xml
  app/src/main/res/layout/fragment_error_missing.xml
  app/src/main/res/layout/fragment_error_missing_app_bar.xml
  app/src/main/res/layout/fragment_error_server_etc.xml
  app/src/main/res/layout/fragment_error_server_etc_app_bar.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_smoking_addiction_test_result.xml
  app/src/main/res/layout/recyclerview_search_recommend.xml
  app/src/main/res/values/strings.xml
Labels: feature, design
